<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'About Us' => '關於我們',
	'About Us Description' => '始創于1995年的萬宜珠寶是一家香港老字號，多年來以客為本，以客為尊，提供各類千足金飾品、鑽石K金飾品及進口天然翡翠飾品。始創于1995年的萬宜珠寶是一家香港老字號，多年來以客為本，以客為尊，提供各類千足金飾品、鑽石K金飾品及進口天然翡翠飾品。',
    'Contact Us' => '聯絡我們',
    'Privacy Statement' => '私隱聲明',
    'Site Map' => '網站地圖',
    'Introduction' => '這裏是介紹文。',
    'Address' => '上環德輔道中',
];
