<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Product Code' => '产品型号',
	'Product Information' => '产品资讯',
	
	'About Us' => '关于我们',
	'About Us Description' => '始创于1995年的万宜珠宝是​​一家香港老字号，多年来以客为本，以客为尊，提供各类千足金饰品、钻石K金饰品及进口天然翡翠饰品。始创于1995年的万宜珠宝是​​一家香港老字号，多年来以客为本，以客为尊，提供各类千足金饰品、钻石K金饰品及进口天然翡翠饰品。',
	'Contact Us' => '联络我们',
	'Privacy Statement' => '私隐声明',
	'Site Map' => '网站地图',
	'Introduction' => '这里是介绍文。',
    'Address' => '上环德辅道中',
];
